"""Evaluation harness: golden-set scoring + data-drift check.

Golden set: 14 questions scored on segment accuracy, evidence coverage,
faithfulness, and correct routing of the conditional second round.

Drift check: compares recent vs baseline loss ratios per segment using
the same pandas maths the agents use.

Run:  python evaluate.py         (writes EVAL_RESULTS.md)
"""

import json
import os

import pandas as pd

from graph import build_graph
from guardrails import _known_sources
from llm import get_llm
from retriever import TagFilterRetriever

HERE = os.path.dirname(__file__)
DATA_DIR = os.path.join(HERE, "data")
DRIFT_THRESHOLD_PTS = 0.05  # 5-point loss-ratio move vs baseline is worth flagging


# --------------------------------------------------------------------------------------
# Golden-set scoring
# --------------------------------------------------------------------------------------

def _score_one(case: dict, result: dict) -> dict:
    """Score a single question against expected answers."""
    rec = result["recommendation"]
    findings = {k: result[k] for k in ("claims", "conversion", "market") if result.get(k)}

    evidence_sources = {e.source for e in rec.evidence}
    known = _known_sources(findings)

    segment_ok = rec.segment == case["expected_segment"]
    evidence_ok = set(case["expected_sources"]).issubset(evidence_sources)
    # Faithfulness: nothing on the page cites a source outside what the agents retrieved.
    faithfulness_ok = evidence_sources.issubset(known) and len(rec.evidence) > 0
    # Orchestration: the conditional second round fired iff it should have.
    routing_ok = bool(result.get("second_round")) == case["expect_second_round"]

    claims_flags = findings["claims"].flags if "claims" in findings else []
    deterioration_ok = ("loss_ratio_deteriorating" in claims_flags) == case["expect_deterioration"]

    passed = all([segment_ok, evidence_ok, faithfulness_ok, routing_ok, deterioration_ok])
    return {
        "id": case["id"],
        "segment_ok": segment_ok,
        "evidence_ok": evidence_ok,
        "faithful_ok": faithfulness_ok,
        "routing_ok": routing_ok,
        "deterioration_ok": deterioration_ok,
        "passed": passed,
        "got_segment": rec.segment,
        "second_round": bool(result.get("second_round")),
    }


def run_golden_set(app, cases: list[dict]) -> list[dict]:
    """Run every golden-set question through the graph and score it."""
    results = []
    for case in cases:
        out = app.invoke({"question": case["question"]})
        results.append(_score_one(case, out))
        r = results[-1]
        mark = "PASS" if r["passed"] else "FAIL"
        print(f"  {r['id']}  {mark}  segment={r['got_segment']:<14} 2nd_round={r['second_round']}")
    return results


# --------------------------------------------------------------------------------------
# Data drift check
# --------------------------------------------------------------------------------------

def drift_check() -> list[dict]:
    """Compare recent 3-month loss ratio to 6-month baseline per segment.

    Recomputes LR from source columns, same as the claims agent.
    """
    df = pd.read_csv(os.path.join(DATA_DIR, "claims_performance.csv"))
    rows = []
    for seg, g in df.groupby("segment"):
        g = g.sort_values("month")
        baseline = g.head(6)
        recent = g.tail(3)
        base_lr = baseline["claims_cost"].sum() / baseline["earned_premium"].sum()
        recent_lr = recent["claims_cost"].sum() / recent["earned_premium"].sum()
        drift = recent_lr - base_lr
        rows.append({
            "segment": seg,
            "baseline_loss_ratio": round(base_lr, 4),
            "recent_loss_ratio": round(recent_lr, 4),
            "drift_pts": round(drift, 4),
            "drift_flagged": bool(drift >= DRIFT_THRESHOLD_PTS),
        })
    return sorted(rows, key=lambda r: r["drift_pts"], reverse=True)


# --------------------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------------------

def write_report(scores: list[dict], drift: list[dict]):
    """Write EVAL_RESULTS.md from the run data."""
    passed = sum(s["passed"] for s in scores)
    total = len(scores)

    lines = ["# Evaluation Results", "",
             f"_Generated by `python evaluate.py`. {passed}/{total} golden-set questions passed._", "",
             "## Golden set", "",
             "| ID | Segment correct | Evidence cited | Faithful | Routing correct | Deterioration correct | Result |",
             "|----|----|----|----|----|----|----|"]
    for s in scores:
        tick = lambda b: "✅" if b else "❌"
        lines.append(f"| {s['id']} | {tick(s['segment_ok'])} | {tick(s['evidence_ok'])} | "
                     f"{tick(s['faithful_ok'])} | {tick(s['routing_ok'])} | "
                     f"{tick(s['deterioration_ok'])} | {'PASS' if s['passed'] else 'FAIL'} |")

    lines += ["", "**Scoring dimensions**",
              "- **Segment correct** — the copilot routed to the right segment.",
              "- **Evidence cited** — every expected source appears in the evidence trail.",
              "- **Faithful** — no evidence item cites a source outside what the agents retrieved.",
              "- **Routing correct** — the conditional second round fired iff a material deterioration was present.",
              "- **Deterioration correct** — the Claims agent's loss-ratio flag matches ground truth.",
              "", "## Data drift check", "",
              "Recent 3-month loss ratio vs 6-month baseline, per segment (recompute-from-source):", "",
              "| Segment | Baseline LR | Recent LR | Drift (pts) | Flagged |",
              "|----|----|----|----|----|"]
    for d in drift:
        lines.append(f"| {d['segment']} | {d['baseline_loss_ratio']:.0%} | {d['recent_loss_ratio']:.0%} | "
                     f"{d['drift_pts'] * 100:+.1f} | {'🚩 yes' if d['drift_flagged'] else '—'} |")
    lines += ["", "> The drift check independently flags **Motor 25-34** — the same segment the "
              "agents surface — from the data alone, without the LLM in the loop.", ""]

    with open(os.path.join(HERE, "EVAL_RESULTS.md"), "w") as f:
        f.write("\n".join(lines))
    print(f"\n📝  Wrote EVAL_RESULTS.md  ({passed}/{total} passed)")


if __name__ == "__main__":
    with open(os.path.join(HERE, "golden_set.json")) as f:
        cases = json.load(f)["questions"]

    app = build_graph(get_llm(), TagFilterRetriever())

    print("Running golden set…")
    scores = run_golden_set(app, cases)

    print("\nRunning drift check…")
    drift = drift_check()
    for d in drift:
        print(f"  {d['segment']:<14} drift {d['drift_pts'] * 100:+.1f}pts  {'FLAGGED' if d['drift_flagged'] else ''}")

    write_report(scores, drift)
